# Generated by Django 5.1.3 on 2024-12-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="1e9c08", max_length=6),
        ),
    ]
