# Generated by Django 5.1.3 on 2024-12-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_otptoken_otp_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="c0bc49", max_length=6),
        ),
    ]
